graph TD
Assembly-CSharp
Assembly-CSharp-->Prototypes.DropperTest
Assembly-CSharp-->Tools
Assembly-CSharp-->NestedTODO.Editor
Assembly-CSharp-->Unity.Entities.Properties
Assembly-CSharp-->Unity.Scenes.Editor
Assembly-CSharp-->bolt.scripts.aoi
Assembly-CSharp-->RainbowAssets.RainbowFolders.Editor
Assembly-CSharp-->Unity.Mathematics.Extensions.Hybrid
Assembly-CSharp-->Photon.WebGL
Assembly-CSharp-->Unity.Entities.BuildUtils
Assembly-CSharp-->Unity.Entities.Hybrid.EndToEnd.Tests
Assembly-CSharp-->CCC.NetSerializer.Impl
Assembly-CSharp-->bolt.scripts.editor
Assembly-CSharp-->TestScripts
Assembly-CSharp-->CCC.FragmentTree
Assembly-CSharp-->Prototypes.Alex
Assembly-CSharp-->Examples
Assembly-CSharp-->CCC.UPaint.Sample
Assembly-CSharp-->CCC.EditorNotes
Simulation.Game
Simulation.Game-->Simulation.Engine
CCC.Debug
CCC.Debug-->CCC.Core
Simulation.EventSystem
Simulation.EventSystem-->Simulation.EngineBase
Prototypes.DropperTest
Prototypes.DropperTest-->CCC.Core
Tools
Tools-->Game
CCC.UI
CCC.UI-->CCC.Online
Game
Game-->BoltKit
Game-->CCC.UI
Game-->Simulation.Game
Game-->SimulationIO
Game-->Unity.Transforms.Hybrid
NestedTODO.Editor
Unity.Entities.Properties
Unity.Entities.Properties-->Unity.Transforms
CCC.UPaint
CCC.UPaint-->CCC.Core
Unity.Entities.StaticTypeRegistry
BoltKit
Simulation.EngineBase
Simulation.EngineBase-->Simulation.Core
Simulation.Core
Simulation.Core-->CCC.FixMath
RainbowAssets.Core
CCC.FixMath
CCC.FixMath-->CCC.NetSerializer
CCC.NetSerializer
CCC.NetSerializer-->CCC.Core
Unity.Scenes.Hybrid
Unity.Scenes.Hybrid-->Unity.Entities.Hybrid
Unity.Scenes.Hybrid-->Unity.Transforms
Unity.Scenes.Editor
Unity.Scenes.Editor-->Unity.Scenes.Hybrid
Unity.Mathematics.Extensions
bolt.scripts.aoi
RainbowAssets.RainbowFolders.Editor
RainbowAssets.RainbowFolders.Editor-->RainbowAssets.Editor
Unity.Mathematics.Extensions.Hybrid
Unity.Mathematics.Extensions.Hybrid-->Unity.Mathematics.Extensions
Photon.WebGL
Unity.Entities.BuildUtils
CCC.Core
CCC.Core-->DOTweenModules
CCC.Core-->Unity.Entities.Hybrid
CCC.Core-->Unity.Transforms
Unity.Entities.Hybrid.EndToEnd.Tests
Unity.Entities.Hybrid.EndToEnd.Tests-->Unity.Scenes.Hybrid
Unity.Entities.Hybrid
Unity.Entities.Hybrid-->Unity.Entities
CCC.NetSerializer.Impl
CCC.NetSerializer.Impl-->Game
bolt.scripts.editor
bolt.scripts.editor-->BoltKit
RainbowAssets.Editor
RainbowAssets.Editor-->RainbowAssets.Core
TestScripts
TestScripts-->Game
Unity.Entities
Unity.Entities-->Unity.Mathematics.Extensions
Unity.Entities-->Unity.Entities.StaticTypeRegistry
Unity.Transforms
Unity.Transforms-->Unity.Entities
CCC.FragmentTree
Simulation.Engine
Simulation.Engine-->Simulation.EventSystem
Prototypes.Alex
Prototypes.Alex-->Game
DOTweenModules
Examples
Examples-->CCC.Core
CCC.UPaint.Sample
CCC.UPaint.Sample-->CCC.UPaint
CCC.Online
CCC.Online-->CCC.Debug
CCC.Online-->CCC.NetSerializer
CCC.EditorNotes
CCC.EditorNotes-->CCC.Core
Unity.Transforms.Hybrid
Unity.Transforms.Hybrid-->Unity.Entities.Hybrid
Unity.Transforms.Hybrid-->Unity.Transforms
SimulationIO
SimulationIO-->CCC.Online
SimulationIO-->Simulation.Core
DocCodeSamples
DocCodeSamples-->Unity.Transforms
Presentation
Presentation-->Simulation.Game
Presentation-->SimulationIO
SimulationIO.Core
SimulationIO.Core-->CCC.Online
SimulationIO.Core-->Simulation.Engine
Unity.Burst.Tests
Unity.Entities.AutoCreation.Tests
Unity.Entities.AutoCreation.Tests-->Unity.Entities.Tests
Unity.Entities.Tests
Unity.Entities.Tests-->Unity.Transforms
Unity.Entities.CodeGen
Unity.Entities.CodeGen-->Unity.Entities
Unity.Entities.CodeGen.Tests
Unity.Entities.CodeGen.Tests-->Unity.Entities.CodeGen
Unity.Entities.CodeGen.Tests-->Unity.Entities.CodeGen.Tests.TestTypes
Unity.Entities.CodeGen.Tests-->Unity.Entities.Hybrid
Unity.Entities.CodeGen.Tests.TestTypes
Unity.Entities.CodeGen.Tests.TestTypes-->Unity.Entities
Unity.Entities.Editor.Tests
Unity.Entities.Editor.Tests-->Unity.Entities.Tests
Unity.Entities.Hybrid.CodeGen
Unity.Entities.Hybrid.CodeGen-->Unity.Entities.Hybrid
Unity.Entities.Hybrid.CodeGen-->Unity.Entities.CodeGen
Unity.Entities.Hybrid.CodeGen.Tests
Unity.Entities.Hybrid.CodeGen.Tests-->Unity.Entities.CodeGen.Tests
Unity.Entities.Hybrid.CodeGen.Tests-->Unity.Entities.Hybrid.CodeGen
Unity.Entities.Hybrid.CodeGen.Tests-->Unity.Entities.Hybrid.Tests
Unity.Entities.Hybrid.Tests
Unity.Entities.Hybrid.Tests-->Unity.Entities.Tests
Unity.Entities.Hybrid.Tests-->Unity.Entities.TestComponents
Unity.Entities.Hybrid.Tests-->Unity.Transforms.Hybrid
Unity.Entities.TestComponents
Unity.Entities.TestComponents-->Unity.Entities.Hybrid
Unity.Entities.Properties.Tests
Unity.Entities.Properties.Tests-->Unity.Entities.Properties
Unity.Entities.Properties.Tests-->Unity.Entities.Tests
Unity.Scenes.Editor.Tests
Unity.Scenes.Editor.Tests-->Unity.Entities.Tests
Unity.Scenes.Editor.Tests-->Unity.Scenes.Editor
Unity.Scenes.Hybrid.Tests
Unity.Scenes.Hybrid.Tests-->Unity.Entities.Tests
Unity.Scenes.Hybrid.Tests-->Unity.Scenes.Editor
Unity.Scenes.Hybrid.Tests.Playmode
Unity.Scenes.Hybrid.Tests.Playmode-->Unity.Entities.Tests
Unity.Scenes.Hybrid.Tests.Playmode-->Unity.Scenes.Editor
Unity.Transforms.Tests
Unity.Transforms.Tests-->Unity.Entities.Tests
