graph TD
bolt.scripts.aoi
bolt.scripts.editor
bolt.scripts.editor-->BoltKit
BoltKit
CCC.Core
CCC.Core-->DOTweenModules
DOTweenModules
CCC.Debug
CCC.Debug-->CCC.Core
CCC.EditorNotes
CCC.EditorNotes-->CCC.Core
CCC.FixMath
CCC.FixMath-->CCC.NetSerializer
CCC.NetSerializer
CCC.NetSerializer-->CCC.Core
CCC.FragmentTree
CCC.NetSerializer.Impl
CCC.NetSerializer.Impl-->Game
Game
Game-->BoltKit
Game-->CCC.Debug
Game-->CCC.Online
Game-->CCC.UI
Game-->Simulation.Game
Simulation.Core
Simulation.Core-->CCC.FixMath
Simulation.Engine
Simulation.Engine-->Simulation.Core
Simulation.Game
Simulation.Game-->Simulation.Engine
CCC.Online
CCC.Online-->CCC.NetSerializer
CCC.UI
CCC.UI-->CCC.Core
Examples
Examples-->CCC.Core
NestedTODO.Editor
Photon.WebGL
Prototypes.Alex
Prototypes.Alex-->Game
Prototypes.DropperTest
Prototypes.DropperTest-->CCC.Core
RainbowAssets.Core
RainbowAssets.Editor
RainbowAssets.Editor-->RainbowAssets.Core
RainbowAssets.RainbowFolders.Editor
RainbowAssets.RainbowFolders.Editor-->RainbowAssets.Editor
TestScripts
TestScripts-->Game
Tools
Tools-->Game
